/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.arshadm.unchecked_cast

import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test


class LibraryTest {
    @Test
    fun kotlinObjectInstance() {
        assertThat(PrivateObjectX::class.java.kotlinObjectInstance).isSameAs(PrivateObjectX)
    }

    object PublicObject
    private object PrivateObjectX
    protected object ProtectedObject

    private class PrivateClass123
}
